Repository scientific-python/upload-nightly-action, pull requests merged in 2023-08, with the labels that each got.

#27 CI: Add test workflow for action
  .github/workflows/ci.yml
  tests/test_package/README.md
  tests/test_package/pyproject.toml
  tests/test_package/src/test_package/__init__.py
Labels: CI

#33 CI: Remove package versions older than 30 days
  .github/workflows/remove-wheels.yml
Labels: enhancement, CI

#37 DOC: some cleanup in the readme, and some heading hierarcy
  README.md
Labels: documentation

#38 DOC: add channel retention policy
  README.md
Labels: documentation
