Repository scientific-python/upload-nightly-action, pull requests merged in 2024-01, with the labels that each got.

#47 ENH: Add optional `anaconda_nightly_upload_organization` argument
  README.md
  action.yml
  cmd.sh
Labels: documentation, enhancement

#54 CI: Add test for uploads with multiple labels
  .github/workflows/ci.yml
Labels: CI

#55 FIX: Remove environment print for security
  cmd.sh
Labels: bug

#56 DOC: Update action commit SHA to the 0.3.0 tag
  README.md
Labels: documentation

#59 CI: Group dependabot updates
  .github/dependabot.yml
Labels: CI
